version: "5.1.2"

# Build phase

# Run phase
services:
  petstore_api_app:
    image: petstore_api_app
    #build: .
    container_name: petstore_api_app
    ports:
      - 8080:8080
    environment:
      ENV_POSTGRES_HOST: ${ENV_POSTGRES_HOST}
      ENV_POSTGRES_PORT: ${ENV_POSTGRES_PORT}
      ENV_POSTGRES_DB_NAME: ${ENV_POSTGRES_DB_NAME}
      ENV_POSTGRES_USERNAME: ${ENV_POSTGRES_USERNAME}
      ENV_POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
    networks:
      - petstore_postgres_network
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres_petsdb
    #    env_file: ./.env
    ports:
      - ${ENV_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USERNAME: ${ENV_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
    #      POSTGRES_DB: ${ENV_POSTGRES_DB_NAME}
    volumes:
      - C:\Users\Thomas_Mylonas\Documents\_Projects_Data\postgres_data:/var/lib/postgresql
    networks:
      - petstore_postgres_network
    restart: unless-stopped

#volumes:
#  pg_data:

networks:
  petstore_postgres_network:
    driver: bridge
