FROM eclipse-temurin:21-jre-alpine
LABEL authors="Thomas_Mylonas"

COPY target/petstore_api_app-0.0.1-SNAPSHOT.jar .

ENV ENV_POSTGRES_HOST=${ENV_POSTGRES_HOST}
ENV ENV_POSTGRES_PORT =${ENV_POSTGRES_PORT}
ENV ENV_POSTGRES_DB_NAME = ${ENV_POSTGRES_DB_NAME}
ENV ENV_POSTGRES_USERNAME=${ENV_POSTGRES_USERNAME}
ENV ENV_POSTGRES_PASSWORD = ${ENV_POSTGRES_PASSWORD}

#ENV DOCKERFILE_POSTGRES_HOST=${ENV_POSTGRES_HOST}
#ENV DOCKERFILE_POSTGRES_PORT =${ENV_POSTGRES_PORT}
#ENV DOCKERFILE_POSTGRES_DB_NAME = ${ENV_POSTGRES_DB_NAME}
#ENV DOCKERFILE_POSTGRES_USERNAME=${ENV_POSTGRES_USERNAME}
#ENV DOCKERFILE_POSTGRES_PASSWORD = ${ENV_POSTGRES_PASSWORD}

EXPOSE 8080

ENTRYPOINT ["java", "-jar" , "petstore_api_app-0.0.1-SNAPSHOT.jar"]
