#Datasource - H2-Database: Basic properties
spring:
  datasource:
    url: jdbc:postgresql://${ENV_POSTGRES_HOST}:${ENV_POSTGRES_PORT}/${ENV_POSTGRES_DB_NAME}
    username: ${ENV_POSTGRES_USERNAME}
    password: ${ENV_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${ENV_POSTGRES_USERNAME}
    password: ${ENV_POSTGRES_PASSWORD}
    baseline-description: "Create_Schema"
    baseline-version: 0
