server:
  port: 8080

#Datasource - Oracle Database
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:oracledb
#    username: petstoredb
#    password: aaaa
#    driver-class-name: oracle.jdbc.OracleDriver

#Datasource - H2-Database: Basic properties
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        show_sql: true
        format_sql: true
  #Datasource - H2-Database: Other properties
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  #Datasource - H2-Database: schema/data locations
  sql:
    init:
      #continue-on-error: true
      schema-locations: classpath:sql_queries/schema.sql
      #data-locations: classpath:sql_queries/data.sql

logging:
  level:
    org:
      hibernate:
        sql: debug

#Not-existing properties
#security.basic.enable=false
#security.ignored=/**
#logging.level.org.hibernate.sql=debug
