#server.port=8080
#Datasource
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:oracledb
spring.datasource.username=petstoredb
spring.datasource.password=aaaa
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.sql.init.continue-on-error=true
#Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.sql=debug
#Thymeleaf
spring.thymeleaf.cache=false
#
#security.basic.enable=false
#security.ignored=/**

