server:
  port: 8080

#Datasource - H2-Database: Basic properties
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: false

  #Datasource - H2-Database: Other properties
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

logging:
  level:
    org:
      hibernate:
        sql: debug

stacktrace:
  print: false

#Not-existing properties
#security.basic.enable=false
#security.ignored=/**
#logging.level.org.hibernate.sql=debug
