server:
  port: 8080
  ssl:
    enabled: true
    key-alias: petstore_keystore
    key-store: classpath:ssl/petstore_keystore.p12
    key-store-type: PKCS12
    #key-password: ${ENV_SSL_KEYSTORE_PASSWORD}
    key-store-password: ${ENV_SSL_KEYSTORE_PASSWORD}
    #enabled-protocols:
    #  - TLSv1.3

#Datasource - H2-Database: Basic properties
spring:
  application:
    name: PetstoreApiApp
  profiles:
    active: prod
  config:
    import: optional:file:.env[.properties]
#  security:
#    oauth2:
#      client:
#        registration:
#          auth_code_thymeleaf_client:
#            client-id: auth_code_thymeleaf_client
#            client-secret: OSVbZyU9NtOiWnAO1wqf0J6DRsrcja9B
#            scope:
#              - openid
#              - profile
#              - roles
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/auth_code_thymeleaf_client
#          client_creds_client:
#            client-id: client_creds_client
#            client-secret: j5POznBiG37q0gfjPyGm1WQRw9simH0J
#            scope:
#              - openid
#              - profile
#              - roles
#            authorization-grant-type: client_credentials
#        provider:
#          keyloak:
#            issuer-uri: http://localhost:9000/realms/oauth2_realm_tom
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:9000/realms/oauth2_realm_tom/protocol/openid-connect/certs

logging:
  level:
    org:
      hibernate:
        sql: debug

#Not-existing properties
#security.basic.enable=false
#security.ignored=/**
#logging.level.org.hibernate.sql=debug
