#Datasource - H2-Database: Basic properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petsdb
    username: postgres
    password: tom
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
