package com.thomasmylonas.petstore_api_app.helpers;

import com.thomasmylonas.petstore_api_app.api.dtos.category_dtos.CategoryRequestDto;
import com.thomasmylonas.petstore_api_app.api.dtos.order_dtos.OrderRequestDto;
import com.thomasmylonas.petstore_api_app.api.dtos.pet_dtos.PetRequestDto;
import com.thomasmylonas.petstore_api_app.api.dtos.photo_url_dtos.PhotoUrlRequestDto;
import com.thomasmylonas.petstore_api_app.api.dtos.tag_dtos.TagRequestDto;
import com.thomasmylonas.petstore_api_app.api.dtos.user_dtos.UserRequestDto;
import com.thomasmylonas.petstore_api_app.enums.OrderStatus;
import com.thomasmylonas.petstore_api_app.enums.PetStatus;

import java.util.List;

public class TestDataProvider {

    public static List<PetRequestDto> PET_REQUEST_DTOS = List.of(
            PetRequestDto.builder()
                    .name("azor")
                    .status(PetStatus.AVAILABLE.getValue())
                    .categoryRequestDto(CategoryRequestDto.builder()
                            .name("dog")
                            .build())
                    .tagRequestDtos(List.of(
                                    TagRequestDto.builder().name("azor123").build(),
                                    TagRequestDto.builder().name("azor456").build()
                            )
                    )
                    .photoUrlRequestDtos(
                            List.of(
                                    PhotoUrlRequestDto.builder().name("htttp://www.dogs.azor1.com").build(),
                                    PhotoUrlRequestDto.builder().name("htttp://www.dogs.azor2.com").build()
                            )
                    )
                    .build(),
            PetRequestDto.builder()
                    .name("bo")
                    .status(PetStatus.AVAILABLE.getValue())
                    .categoryRequestDto(CategoryRequestDto.builder()
                            .name("dog")
                            .build())
                    .tagRequestDtos(List.of(
                                    TagRequestDto.builder().name("bo123").build(),
                                    TagRequestDto.builder().name("bo456").build()
                            )
                    )
                    .photoUrlRequestDtos(
                            List.of(
                                    PhotoUrlRequestDto.builder().name("htttp://www.dogs.bo1.com").build(),
                                    PhotoUrlRequestDto.builder().name("htttp://www.dogs.bo2.com").build()
                            )
                    )
                    .build(),
            PetRequestDto.builder()
                    .name("tom")
                    .status(PetStatus.AVAILABLE.getValue())
                    .categoryRequestDto(CategoryRequestDto.builder()
                            .name("cat")
                            .build())
                    .tagRequestDtos(List.of(
                                    TagRequestDto.builder().name("tom123").build()
                            )
                    )
                    .photoUrlRequestDtos(
                            List.of(
                                    PhotoUrlRequestDto.builder().name("htttp://www.cats.tom.com").build()
                            )
                    )
                    .build(),
            PetRequestDto.builder()
                    .name("karisha")
                    .status(PetStatus.SOLD.getValue())
                    .categoryRequestDto(CategoryRequestDto.builder()
                            .name("cat")
                            .build())
                    .tagRequestDtos(List.of(
                                    TagRequestDto.builder().name("karisha123").build(),
                                    TagRequestDto.builder().name("karisha456").build()
                            )
                    )
                    .photoUrlRequestDtos(
                            List.of(
                                    PhotoUrlRequestDto.builder().name("htttp://www.cats.karisha1.com").build(),
                                    PhotoUrlRequestDto.builder().name("htttp://www.cats.karisha2.com").build(),
                                    PhotoUrlRequestDto.builder().name("htttp://www.cats.karisha3.com").build(),
                                    PhotoUrlRequestDto.builder().name("htttp://www.cats.karisha4.com").build()
                            )
                    )
                    .build(),
            PetRequestDto.builder()
                    .name("stepasha")
                    .status(PetStatus.SOLD.getValue())
                    .categoryRequestDto(CategoryRequestDto.builder()
                            .name("cat")
                            .build())
                    .tagRequestDtos(List.of(
                                    TagRequestDto.builder().name("stepasha123").build(),
                                    TagRequestDto.builder().name("stepasha456").build(),
                                    TagRequestDto.builder().name("stepasha789").build()
                            )
                    )
                    .photoUrlRequestDtos(
                            List.of(
                                    PhotoUrlRequestDto.builder().name("htttp://www.cats.stepasha.com").build()
                            )
                    )
                    .build(),
            PetRequestDto.builder()
                    .name("foo")
                    .status(PetStatus.PENDING.getValue())
                    .categoryRequestDto(CategoryRequestDto.builder()
                            .name("fish")
                            .build())
                    .tagRequestDtos(List.of(
                                    TagRequestDto.builder().name("foo123").build()
                            )
                    )
                    .photoUrlRequestDtos(
                            List.of(
                                    PhotoUrlRequestDto.builder().name("htttp://www.fishes.foo.com").build()
                            )
                    )
                    .build(),
            PetRequestDto.builder()
                    .name("bar")
                    .status(PetStatus.PENDING.getValue())
                    .categoryRequestDto(CategoryRequestDto.builder()
                            .name("bird")
                            .build())
                    .tagRequestDtos(List.of(
                                    TagRequestDto.builder().name("bar123").build(),
                                    TagRequestDto.builder().name("bar456").build()
                            )
                    )
                    .photoUrlRequestDtos(
                            List.of(
                                    PhotoUrlRequestDto.builder().name("htttp://www.birds.bar1.com").build(),
                                    PhotoUrlRequestDto.builder().name("htttp://www.birds.bar2.com").build()
                            )
                    )
                    .build(),
            PetRequestDto.builder()
                    .name("shssss")
                    .status(PetStatus.PENDING.getValue())
                    .categoryRequestDto(CategoryRequestDto.builder()
                            .name("snake")
                            .build())
                    .tagRequestDtos(List.of(
                                    TagRequestDto.builder().name("shssss123").build()
                            )
                    )
                    .photoUrlRequestDtos(
                            List.of(
                                    PhotoUrlRequestDto.builder().name("htttp://www.snakes.shssss.com").build()
                            )
                    )
                    .build()
    );

    public static List<OrderRequestDto> ORDER_REQUEST_DTOS = List.of(
            OrderRequestDto.builder()
                    .petId(2)
                    .quantity(4)
                    .status(OrderStatus.PLACED.getValue())
                    .complete(true)
                    .build(),
            OrderRequestDto.builder()
                    .petId(3)
                    .quantity(2)
                    .status(OrderStatus.APPROVED.getValue())
                    .complete(false)
                    .build(),
            OrderRequestDto.builder()
                    .petId(3)
                    .quantity(4)
                    .status(OrderStatus.PLACED.getValue())
                    .complete(true)
                    .build(),
            OrderRequestDto.builder()
                    .petId(1)
                    .quantity(4)
                    .status(OrderStatus.APPROVED.getValue())
                    .complete(false)
                    .build(),
            OrderRequestDto.builder()
                    .petId(4)
                    .quantity(4)
                    .status(OrderStatus.DELIVERED.getValue())
                    .complete(true)
                    .build()
    );

    public static final List<UserRequestDto> USER_REQUEST_DTOS = List.of(
            UserRequestDto.builder()
                    .username("tom")
                    .firstName("Thomas")
                    .lastName("Mylonas")
                    .email("tom@mail.com")
                    .password("tom")
                    .phone("000000000")
                    .userStatus(0)
                    .build(),
            UserRequestDto.builder()
                    .username("laur")
                    .firstName("Laurentiu")
                    .lastName("Spilca")
                    .email("laur@mail.com")
                    .password("laur")
                    .phone("111111111")
                    .userStatus(1)
                    .build(),
            UserRequestDto.builder()
                    .username("jose")
                    .firstName("Jose")
                    .lastName("Paumard")
                    .email("jose@mail.com")
                    .password("jose")
                    .phone("222222222")
                    .userStatus(0)
                    .build(),
            UserRequestDto.builder()
                    .username("venkat")
                    .firstName("Venkat")
                    .lastName("Subramaniam")
                    .email("venkat@mail.com")
                    .password("venkat")
                    .phone("333333333")
                    .userStatus(1)
                    .build(),
            UserRequestDto.builder()
                    .username("vlad")
                    .firstName("Vlad")
                    .lastName("Mihalcea")
                    .email("vlad@mail.com")
                    .password("vlad")
                    .phone("444444444")
                    .userStatus(0)
                    .build()
    );
}
