
-- General
-- CREATE SEQUENCE ID_SEQUENCE
--     INCREMENT BY 1
--     START WITH 10
--     MINVALUE 10
--     MAXVALUE 15
--     CYCLE
--     CACHE 2;

CREATE SEQUENCE ID_SEQUENCE_PET
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    CACHE 2;

CREATE SEQUENCE ID_SEQUENCE_CATEGORY
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    CACHE 2;

CREATE SEQUENCE ID_SEQUENCE_TAG
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    CACHE 2;

CREATE SEQUENCE ID_SEQUENCE_PHOTO_URL
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    CACHE 2;

CREATE SEQUENCE ID_SEQUENCE_STATUS
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    CACHE 2;

-- ***************************************

DROP SEQUENCE ID_SEQUENCE_PET;
DROP SEQUENCE ID_SEQUENCE_CATEGORY;
DROP SEQUENCE ID_SEQUENCE_TAG;
DROP SEQUENCE ID_SEQUENCE_PHOTO_URL;
DROP SEQUENCE ID_SEQUENCE_STATUS;